# (PART) Étapes {-}

# Étape 1 : `r iti_etape$Details$Descr_Villes[1]`

```{r, echo=FALSE}
Etape <-1


heureDep <- iti_etape$Details$time_depart[Etape]

heureArr <- iti_etape$Details$time_arrivee[Etape]

date_format <- format(iti_etape$Details$Date[Etape], format = "%A, %d %B %Y", locale = locale("fr"))

```


## `r date_format` {-}

 **`r iti_etape$Details$KM_Total[Etape]` km**


Le commanditaire d'étape est `r iti_etape$Details$Commanditaire[Etape]`. 

## Sommaire

- `r iti_etape$Details$KM_Neutres[Etape]` km neutralisés au départ   
- Sans circuit d'arrivée

----------------------------------------------------
                                              Heure
----------------- ----------------------------------
Départ                                  `r heureDep`

Arrivée finale                         `r heureArr`
----------------------------------------------------

## Parcours


```{r echo=FALSE}
# opts_chunk$set(tidy = FALSE, comment = NA,
#                fig.align = "center",
#                fig.width = 7.5, fig.height = 7.5,
#                fig.retina = 2, cache = FALSE,
#                class.output = "codeout")
```


```{r, echo = FALSE, eval = TRUE, warning = FALSE, fig.align = "center", fig.width = 7.5, fig.height = 7.5}

map <- mapview(parcours[Etape,],
        layer.name = "Parcours",
        color = couleurs$bleuTour,
        map.types = "OpenStreetMap",
        legend = FALSE)

map@map

# - [ ] Problème, carte trop large, je n'arrive pas à la restreindre dans bs4_book

```


<br/>

[Liens vers **Ride with GPS**](`r iti_etape$Details$Liens[Etape]`)

## Élévation


## Description détaillée

```{r echo=FALSE, message=FALSE, warning=FALSE, quiet=TRUE}


tableau_Descrip_Etape(Etape, lang)

```


