# Règlements de séjour 

<!-- valider comment faire la condition Fr ou EN  --> 

- Portez la carte d’accréditation **en tout temps** à l’intérieur de la Centrale. Il est interdit de circuler sans celle-ci.
- Aux repas, présentez votre carte d’accréditation, respectez les quantités permises et rapportez les cabarets après utilisation.
- Respectez le couvre-feu à 23h et l’heure de départ le lundi `r format(iti_etape$Details$Date[7]+ ddays(1) ,format = "%d %B", locale = locale("fr"))` à midi, à moins d’une entente spéciale avec l’administration.
- Réparez et nettoyez les vélos aux endroits prévus à l’extérieur et n’entreposez pas de produits inflammables à l’intérieur.
- Dans les classes, posez les vélos sur les plastiques prévus à cet effet.
- Ne circulez pas sur les vélos à l’intérieur de la centrale administrative.
- Massez les coureurs à l’intérieur des classes ou à la salle prévue à cet effet.
- Ne consommez pas d’alcool ni tabac ni cannabis à l’intérieur de la centrale et sur le terrain de l’école.
- Gardez la centrale propre à l’intérieur et à l’extérieur en utilisant les poubelles. Placez votre poubelle de classe dans le corridor pour la faire vider durant la journée.
- Respectez le personnel et les bénévoles.


# Accommodation rules

- Wear credentials **at all times** in the race headquarters. It is mandatory.
- At meals, show your credentials; take permitted quantities and return trays after use.
- Respect 11:00 PM curfew and noon departure time on Monday, `r format(iti_etape$Details$Date[7]+ ddays(1) ,format = "%B, %d th")`` July 18th unless you have a special agreement with the administration.
- Repair and clean bikes in designated areas outside and do not store flammable products inside.
- In rooms, place bikes on plastic covering.
- Do not ride bikes inside the race headquarters.
- Massages must be given in rooms or in the designated massage room.
- Use of alcohol, tobacco and cannabis are prohibited in the race headquarters and on school property.
- Deposit waste in trash cans and keep the race headquarters clean. Place your room’s trash can in the hallway to have it emptied during the day.
- Respect staff and volunteers.
