# Règlements particuliers

Article 1 – Organisation

:   L’épreuve du Tour de l’Abitibi est une épreuve junior par étapes organisée par Le Tour cycliste de l’Abitibi inc. (1122, 8e Rue - Suite 201, Val-d'Or (Québec) J9P 3N6) sous les règlements et la sanction de l’[Union Cycliste Internationale](https://uci.org) (UCI). 

    Le Tour de l’Abitibi est également sanctionné par la [Fédération Québécoise des Sports Cyclistes](https://fqsc.net/) (FQSC) et [Cyclisme Canada Cycling](https://cyclingcanada.ca/) (CC). 

    L’épreuve est disputée sous le règlement UCI et seule l’échelle des sanctions UCI s’appliquera. Elle se dispute du `r params$dates_compl`.


<!-- [ ] Mettre liens web en html pour avoir redirection target=blank  -->


Article 2 – Type d’épreuve

:   L’épreuve est réservée aux athlètes de la catégorie hommes junior. Elle est inscrite au calendrier UCI Mondial Junior. Pour être considéré comme junior, un coureur doit être né en `r params$annee - 18` ou `r params$annee - 17`. L’épreuve est classée 2.NCupJ et les points UCI seront attribués selon l’article 2.14.040.    

    Les dérogations suivantes ont été accordées par l’UCI à l’organisation du Tour de l’Abitibi :  
    
    * L’épreuve du Tour de l’Abitibi a la possibilité d’accueillir des équipes régionales ou des clubs composés uniquement de coureurs juniors mais ne marquant pas de points UCI (article 2.14.036). De plus, leur maillot devra respecter les articles 1.3.045 à 1.3.047 du Règlement UCI;    
    * L’épreuve du Tour de l’Abitibi compte deux (2) demi-étapes la même journée (article 2.6.010);
   
   
    
Article 3 – Participation
 
:   Tel que mentionné à l’article 2 ci-dessus, l’épreuve est ouverte aux équipes nationales, régionales, de club et aux équipes mixtes. 

    Conformément à l’article 2.14.039 du règlement UCI, le nombre de coureurs par équipe est de minimum quatre (4) et de maximum six (6) coureurs.
    
    Conformément au nouveau règlement UCI (x.x.xxx) adopté pour 2023, il n'y a plus de développement maximum autorisé pour les hommes juniors. 
    


